import { getComponentImage } from "@/lib/component-images";

export type ComponentFilterChip =
  | "all"
  | "arduino"
  | "esp32"
  | "sensors"
  | "motors"
  | "servo"
  | "power"
  | "drivers"
  | "displays"
  | "communication"
  | "iot"
  | "development-boards";

export type ComponentSort = "newest" | "popular" | "price" | "alphabetical";

export type ComponentCategory = Exclude<ComponentFilterChip, "all">;

export type ComponentSpec = {
  label: string;
  value: string;
};

export type ComponentItem = {
  id: string;
  slug: string;
  name: string;
  category: ComponentCategory;
  categoryLabel: string;
  shortDescription: string;
  description: string;
  fullDescription: string;
  image: string;
  specifications: ComponentSpec[];
  compatibility: string[];
  priceRange: string;
  priceValue: number;
  availability: "in-stock" | "limited" | "popular";
  beginnerFriendly: boolean;
  popular: boolean;
  rating: number;
  projectCount: number;
  buyUrl: string;
  operatingVoltage: string;
  currentConsumption: string;
  communicationProtocol: string;
  pins: string;
  compatibleBoards: string[];
  applications: string[];
  exampleProjects: { title: string; slug: string }[];
  datasheetUrl?: string;
  tutorialUrl?: string;
  addedAt: string;
};

export const filterChips: { id: ComponentFilterChip; label: string }[] = [
  { id: "all", label: "All" },
  { id: "arduino", label: "Arduino" },
  { id: "esp32", label: "ESP32" },
  { id: "sensors", label: "Sensors" },
  { id: "motors", label: "Motors" },
  { id: "servo", label: "Servo" },
  { id: "power", label: "Power" },
  { id: "drivers", label: "Drivers" },
  { id: "displays", label: "Displays" },
  { id: "communication", label: "Communication" },
  { id: "iot", label: "IoT" },
  { id: "development-boards", label: "Development Boards" },
];

export const sortOptions: { id: ComponentSort; label: string }[] = [
  { id: "newest", label: "Newest" },
  { id: "popular", label: "Popular" },
  { id: "price", label: "Price" },
  { id: "alphabetical", label: "Alphabetical" },
];

export const featuredComponentSlug = "arduino-uno-r3";

export const catalogCategories = [
  {
    id: "arduino",
    label: "Arduino Boards",
    icon: "cpu" as const,
    count: 12,
    description: "Classic ATmega boards for learning embedded programming.",
  },
  {
    id: "esp32",
    label: "ESP Boards",
    icon: "radio" as const,
    count: 18,
    description: "Wi-Fi and Bluetooth enabled microcontrollers.",
  },
  {
    id: "sensors",
    label: "Sensors",
    icon: "gauge" as const,
    count: 85,
    description: "Ultrasonic, IR, environmental, and motion sensors.",
  },
  {
    id: "motors",
    label: "Motors",
    icon: "zap" as const,
    count: 24,
    description: "DC, stepper, and gear motors for locomotion.",
  },
  {
    id: "power",
    label: "Power Modules",
    icon: "battery" as const,
    count: 16,
    description: "Batteries, holders, and voltage regulators.",
  },
  {
    id: "displays",
    label: "Displays",
    icon: "monitor" as const,
    count: 14,
    description: "OLED, LCD, and LED matrix modules.",
  },
  {
    id: "communication",
    label: "Communication",
    icon: "wifi" as const,
    count: 22,
    description: "Bluetooth, Wi-Fi, and serial modules.",
  },
  {
    id: "mechanical",
    label: "Mechanical Parts",
    icon: "wrench" as const,
    count: 31,
    description: "Chassis, wheels, brackets, and fasteners.",
  },
  {
    id: "tools",
    label: "Tools",
    icon: "tool" as const,
    count: 28,
    description: "Soldering, multimeters, and prototyping tools.",
  },
];

export const learningResources = [
  {
    id: "sensor-guide",
    title: "How to Choose Sensors",
    description: "Match sensor types to your project requirements.",
    href: "/chatbot",
  },
  {
    id: "motor-guide",
    title: "Motor Selection Guide",
    description: "DC vs servo vs stepper — pick the right actuator.",
    href: "/chatbot",
  },
  {
    id: "power-guide",
    title: "Power Supply Guide",
    description: "Voltage, current, and battery safety fundamentals.",
    href: "/chatbot",
  },
  {
    id: "arduino-basics",
    title: "Arduino Basics",
    description: "Pins, sketches, and your first upload.",
    href: "/chatbot",
  },
  {
    id: "esp32-basics",
    title: "ESP32 Basics",
    description: "Wi-Fi setup, GPIO, and dual-core programming.",
    href: "/chatbot",
  },
];

function makeComponent(
  partial: Omit<ComponentItem, "image"> & { slug: string },
): ComponentItem {
  return {
    ...partial,
    image: getComponentImage(partial.slug),
  };
}

export const components: ComponentItem[] = [
  makeComponent({
    id: "1",
    slug: "arduino-uno-r3",
    name: "Arduino UNO R3",
    category: "arduino",
    categoryLabel: "Arduino",
    shortDescription: "The industry-standard 8-bit microcontroller board for beginners.",
    description:
      "ATmega328P-based development board with 14 digital I/O pins, 6 analog inputs, and USB programming.",
    fullDescription:
      "The Arduino UNO R3 is the most widely used microcontroller board in robotics education. It features the ATmega328P processor running at 16 MHz, onboard USB-to-serial conversion, and a standardized pin layout compatible with hundreds of shields and modules. Ideal for first-time builders learning C++ embedded programming.",
    specifications: [
      { label: "MCU", value: "ATmega328P" },
      { label: "Clock", value: "16 MHz" },
      { label: "Digital I/O", value: "14 pins" },
      { label: "Analog In", value: "6 pins" },
    ],
    compatibility: ["HC-SR04", "L298N", "Servo", "DHT11"],
    priceRange: "₹450 – ₹650",
    priceValue: 550,
    availability: "popular",
    beginnerFriendly: true,
    popular: true,
    rating: 4.9,
    projectCount: 48,
    buyUrl: "https://robu.in/product/arduino-uno-r3-board/",
    operatingVoltage: "5V (USB or VIN 7–12V)",
    currentConsumption: "~50 mA active",
    communicationProtocol: "UART (USB serial)",
    pins: "14 digital, 6 analog, 6 PWM",
    compatibleBoards: ["All Arduino shields", "Breadboard modules"],
    applications: ["Learning robotics", "Sensor prototyping", "Motor control"],
    exampleProjects: [
      { title: "Obstacle Avoiding Robot", slug: "obstacle-avoiding-robot" },
      { title: "Line Follower Robot", slug: "line-follower-robot" },
    ],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-01-15",
  }),
  makeComponent({
    id: "2",
    slug: "esp32-devkit",
    name: "ESP32 DevKit",
    category: "esp32",
    categoryLabel: "ESP32",
    shortDescription: "Dual-core Wi-Fi and Bluetooth microcontroller for IoT projects.",
    description:
      "ESP32-WROOM-32 module with integrated Wi-Fi, Bluetooth, and 34 GPIO pins.",
    fullDescription:
      "The ESP32 DevKit combines a powerful dual-core processor with built-in Wi-Fi and Bluetooth LE. Perfect for IoT robotics, remote monitoring, and wireless control applications requiring cloud connectivity.",
    specifications: [
      { label: "MCU", value: "ESP32-WROOM-32" },
      { label: "Cores", value: "Dual-core 240 MHz" },
      { label: "Wi-Fi", value: "802.11 b/g/n" },
      { label: "Bluetooth", value: "BLE 4.2" },
    ],
    compatibility: ["OLED", "MPU6050", "Relay", "Servo"],
    priceRange: "₹350 – ₹550",
    priceValue: 450,
    availability: "in-stock",
    beginnerFriendly: true,
    popular: true,
    rating: 4.8,
    projectCount: 36,
    buyUrl: "https://robu.in/product/esp32-development-board-wifi-bluetooth/",
    operatingVoltage: "3.3V (5V tolerant GPIO)",
    currentConsumption: "80–240 mA (Wi-Fi active)",
    communicationProtocol: "Wi-Fi, BLE, UART, I2C, SPI",
    pins: "34 GPIO, 18 ADC, 16 PWM",
    compatibleBoards: ["Arduino IDE", "PlatformIO", "MicroPython"],
    applications: ["IoT robots", "Wireless control", "Sensor networks"],
    exampleProjects: [
      { title: "IoT Smart Dustbin", slug: "smart-dustbin" },
      { title: "IoT Weather Station", slug: "iot-weather-station" },
    ],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-02-10",
  }),
  makeComponent({
    id: "3",
    slug: "raspberry-pi-5",
    name: "Raspberry Pi 5",
    category: "development-boards",
    categoryLabel: "Development Board",
    shortDescription: "High-performance SBC for computer vision and advanced robotics.",
    description: "Quad-core ARM Cortex-A76 at 2.4 GHz with up to 8 GB RAM.",
    fullDescription:
      "Raspberry Pi 5 delivers desktop-class performance for advanced robotics applications including computer vision, SLAM, and machine learning inference at the edge.",
    specifications: [
      { label: "CPU", value: "Quad-core Cortex-A76" },
      { label: "RAM", value: "4 / 8 GB" },
      { label: "GPIO", value: "40 pins" },
      { label: "USB", value: "2× USB 3.0" },
    ],
    compatibility: ["Camera Module", "HATs", "I2C sensors"],
    priceRange: "₹5,500 – ₹8,500",
    priceValue: 7000,
    availability: "limited",
    beginnerFriendly: false,
    popular: true,
    rating: 4.7,
    projectCount: 22,
    buyUrl: "https://www.amazon.in/s?k=raspberry+pi+5",
    operatingVoltage: "5V 5A USB-C",
    currentConsumption: "Up to 5A peak",
    communicationProtocol: "I2C, SPI, UART, USB, Ethernet",
    pins: "40-pin GPIO header",
    compatibleBoards: ["Pi HATs", "Linux drivers"],
    applications: ["Vision robots", "Edge AI", "Home automation"],
    exampleProjects: [
      { title: "Gesture Controlled Robot", slug: "gesture-controlled-robot" },
    ],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-06-01",
  }),
  makeComponent({
    id: "4",
    slug: "hc-sr04",
    name: "HC-SR04 Ultrasonic Sensor",
    category: "sensors",
    categoryLabel: "Sensor",
    shortDescription: "Measures distance from 2 cm to 400 cm using ultrasonic pulses.",
    description: "4-pin ultrasonic ranging module for obstacle detection.",
    fullDescription:
      "The HC-SR04 emits ultrasonic waves and measures echo time to calculate distance. Essential for obstacle avoidance, parking sensors, and autonomous navigation in beginner robotics projects.",
    specifications: [
      { label: "Range", value: "2–400 cm" },
      { label: "Accuracy", value: "±3 mm" },
      { label: "Angle", value: "15° cone" },
      { label: "Frequency", value: "40 kHz" },
    ],
    compatibility: ["Arduino UNO", "ESP32", "Raspberry Pi"],
    priceRange: "₹60 – ₹120",
    priceValue: 90,
    availability: "popular",
    beginnerFriendly: true,
    popular: true,
    rating: 4.6,
    projectCount: 41,
    buyUrl: "https://robu.in/product/ultrasonic-sensor-hc-sr04/",
    operatingVoltage: "5V DC",
    currentConsumption: "15 mA",
    communicationProtocol: "Digital trigger/echo",
    pins: "VCC, Trig, Echo, GND",
    compatibleBoards: ["Arduino UNO", "ESP32", "NodeMCU"],
    applications: ["Obstacle avoidance", "Distance measurement", "Level sensing"],
    exampleProjects: [
      { title: "Obstacle Avoiding Robot", slug: "obstacle-avoiding-robot" },
    ],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-01-20",
  }),
  makeComponent({
    id: "5",
    slug: "ir-sensor",
    name: "IR Sensor Module",
    category: "sensors",
    categoryLabel: "Sensor",
    shortDescription: "Detects obstacles and line contrast using infrared reflection.",
    description: "Adjustable IR proximity sensor with digital and analog output.",
    fullDescription:
      "IR sensor modules use infrared LEDs and photodiodes to detect objects or surface contrast. Commonly used in line-following robots and proximity detection systems.",
    specifications: [
      { label: "Range", value: "2–30 cm" },
      { label: "Output", value: "Digital + Analog" },
      { label: "Adjust", value: "Potentiometer" },
      { label: "Wavelength", value: "760 nm" },
    ],
    compatibility: ["Arduino UNO", "Line follower chassis"],
    priceRange: "₹25 – ₹50",
    priceValue: 35,
    availability: "in-stock",
    beginnerFriendly: true,
    popular: true,
    rating: 4.5,
    projectCount: 38,
    buyUrl: "https://robu.in/product/ir-sensor-module/",
    operatingVoltage: "3.3–5V",
    currentConsumption: "20 mA",
    communicationProtocol: "Digital GPIO",
    pins: "VCC, GND, OUT",
    compatibleBoards: ["Arduino UNO", "ESP32"],
    applications: ["Line following", "Proximity detection", "Edge detection"],
    exampleProjects: [
      { title: "Line Follower Robot", slug: "line-follower-robot" },
    ],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-03-05",
  }),
  makeComponent({
    id: "6",
    slug: "l298n",
    name: "L298N Motor Driver",
    category: "drivers",
    categoryLabel: "Driver",
    shortDescription: "Dual H-bridge driver for controlling two DC motors.",
    description: "Handles up to 2A per channel with direction and speed control.",
    fullDescription:
      "The L298N module provides bidirectional control of two DC motors using PWM speed regulation. Includes onboard 5V regulator and screw terminals for easy wiring in mobile robot builds.",
    specifications: [
      { label: "Channels", value: "2 (dual H-bridge)" },
      { label: "Current", value: "2A per channel" },
      { label: "Voltage", value: "5–35V motor" },
      { label: "Logic", value: "5V TTL" },
    ],
    compatibility: ["Arduino UNO", "DC Motors", "12V battery"],
    priceRange: "₹120 – ₹200",
    priceValue: 160,
    availability: "popular",
    beginnerFriendly: true,
    popular: true,
    rating: 4.7,
    projectCount: 44,
    buyUrl: "https://robu.in/product/l298n-motor-driver-module/",
    operatingVoltage: "5V logic, 5–35V motor",
    currentConsumption: "2A per motor channel",
    communicationProtocol: "PWM + direction GPIO",
    pins: "IN1–IN4, ENA, ENB, 5V, GND",
    compatibleBoards: ["Arduino UNO", "ESP32"],
    applications: ["Mobile robots", "Car projects", "Conveyor systems"],
    exampleProjects: [
      { title: "Obstacle Avoiding Robot", slug: "obstacle-avoiding-robot" },
      { title: "Bluetooth Car", slug: "bluetooth-car" },
    ],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-01-18",
  }),
  makeComponent({
    id: "7",
    slug: "servo-sg90",
    name: "Servo SG90",
    category: "servo",
    categoryLabel: "Servo",
    shortDescription: "Micro servo with 180° rotation for precise angular control.",
    description: "9g micro servo delivering 1.8 kg·cm torque at 4.8V.",
    fullDescription:
      "The TowerPro SG90 is a lightweight micro servo motor ideal for robotic arms, pan-tilt camera mounts, and steering mechanisms in small robots.",
    specifications: [
      { label: "Torque", value: "1.8 kg·cm" },
      { label: "Rotation", value: "0–180°" },
      { label: "Weight", value: "9 g" },
      { label: "Speed", value: "0.1 s/60°" },
    ],
    compatibility: ["Arduino UNO", "ESP32", "Pi PWM"],
    priceRange: "₹80 – ₹150",
    priceValue: 115,
    availability: "in-stock",
    beginnerFriendly: true,
    popular: true,
    rating: 4.6,
    projectCount: 33,
    buyUrl: "https://robu.in/product/towerpro-sg90-servo-motor/",
    operatingVoltage: "4.8–6V",
    currentConsumption: "100–250 mA (stall)",
    communicationProtocol: "PWM (1–2 ms pulse)",
    pins: "Signal, VCC, GND",
    compatibleBoards: ["Arduino UNO", "ESP32"],
    applications: ["Robotic arms", "Pan-tilt mounts", "Gripper control"],
    exampleProjects: [{ title: "Robotic Arm", slug: "robotic-arm" }],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-02-22",
  }),
  makeComponent({
    id: "8",
    slug: "dc-geared-motor",
    name: "DC Geared Motor",
    category: "motors",
    categoryLabel: "Motor",
    shortDescription: "6V geared DC motor with high torque for robot wheels.",
    description: "100 RPM BO motor with metal gearbox and 65 mm wheel option.",
    fullDescription:
      "Geared DC motors convert high-speed rotation into usable torque for driving robot wheels. The BO (Battery Operated) type is standard in 2WD and 4WD educational robot kits.",
    specifications: [
      { label: "Voltage", value: "3–6V" },
      { label: "RPM", value: "100–200" },
      { label: "Shaft", value: "6 mm D-type" },
      { label: "Gearbox", value: "Metal, 1:48" },
    ],
    compatibility: ["L298N", "Robot chassis", "Wheel 65mm"],
    priceRange: "₹80 – ₹140",
    priceValue: 110,
    availability: "in-stock",
    beginnerFriendly: true,
    popular: true,
    rating: 4.5,
    projectCount: 52,
    buyUrl: "https://robu.in/product/bo-motor-100-rpm/",
    operatingVoltage: "3–6V DC",
    currentConsumption: "200–500 mA",
    communicationProtocol: "N/A (motor)",
    pins: "2 wire (+, −)",
    compatibleBoards: ["L298N", "L293D"],
    applications: ["Wheeled robots", "RC cars", "Conveyor belts"],
    exampleProjects: [
      { title: "Line Follower Robot", slug: "line-follower-robot" },
    ],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-01-25",
  }),
  makeComponent({
    id: "9",
    slug: "stepper-nema17",
    name: "Stepper Motor NEMA17",
    category: "motors",
    categoryLabel: "Motor",
    shortDescription: "Precise open-loop positioning motor for CNC and 3D printers.",
    description: "1.8° step angle, 4-wire bipolar stepper with 40 N·cm holding torque.",
    fullDescription:
      "NEMA17 stepper motors move in discrete steps for precise position control without encoders. Used in 3D printers, CNC machines, and precision positioning systems.",
    specifications: [
      { label: "Step Angle", value: "1.8°" },
      { label: "Torque", value: "40 N·cm" },
      { label: "Size", value: "42×42 mm" },
      { label: "Phases", value: "2 (bipolar)" },
    ],
    compatibility: ["A4988 driver", "Arduino", "CNC shield"],
    priceRange: "₹350 – ₹600",
    priceValue: 475,
    availability: "in-stock",
    beginnerFriendly: false,
    popular: false,
    rating: 4.4,
    projectCount: 14,
    buyUrl: "https://robu.in/product/nema17-stepper-motor/",
    operatingVoltage: "12V",
    currentConsumption: "1.2A per phase",
    communicationProtocol: "Step + direction",
    pins: "4 wire (A+, A−, B+, B−)",
    compatibleBoards: ["Arduino + A4988", "RAMPS"],
    applications: ["CNC", "3D printing", "Precision positioning"],
    exampleProjects: [{ title: "Robotic Arm", slug: "robotic-arm" }],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-04-12",
  }),
  makeComponent({
    id: "10",
    slug: "jumper-wires",
    name: "Jumper Wires",
    category: "development-boards",
    categoryLabel: "Prototyping",
    shortDescription: "Dupont jumper wire set for breadboard connections.",
    description: "40-piece M-M, M-F, F-F assorted jumper cable pack.",
    fullDescription:
      "Jumper wires are essential for prototyping circuits on breadboards without soldering. Available in male-to-male, male-to-female, and female-to-female configurations.",
    specifications: [
      { label: "Length", value: "20 cm" },
      { label: "Quantity", value: "40 pcs" },
      { label: "Types", value: "M-M, M-F, F-F" },
      { label: "Gauge", value: "22 AWG" },
    ],
    compatibility: ["Breadboard", "Arduino", "All modules"],
    priceRange: "₹80 – ₹150",
    priceValue: 115,
    availability: "in-stock",
    beginnerFriendly: true,
    popular: true,
    rating: 4.8,
    projectCount: 60,
    buyUrl: "https://robu.in/product/jumper-wire-40pcs/",
    operatingVoltage: "N/A",
    currentConsumption: "N/A",
    communicationProtocol: "N/A",
    pins: "Dupont connectors",
    compatibleBoards: ["Universal"],
    applications: ["Prototyping", "Testing", "Lab setups"],
    exampleProjects: [],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-01-10",
  }),
  makeComponent({
    id: "11",
    slug: "breadboard",
    name: "Breadboard",
    category: "development-boards",
    categoryLabel: "Prototyping",
    shortDescription: "830-point solderless breadboard for circuit prototyping.",
    description: "Standard half-size breadboard with power rails.",
    fullDescription:
      "Breadboards allow rapid circuit assembly without soldering. The 830-point layout provides ample space for microcontroller modules, sensors, and passive components.",
    specifications: [
      { label: "Points", value: "830 tie-points" },
      { label: "Rails", value: "4 power rails" },
      { label: "Size", value: "165×55 mm" },
      { label: "Material", value: "ABS plastic" },
    ],
    compatibility: ["Arduino", "ESP32", "Jumper wires"],
    priceRange: "₹90 – ₹180",
    priceValue: 135,
    availability: "in-stock",
    beginnerFriendly: true,
    popular: true,
    rating: 4.7,
    projectCount: 55,
    buyUrl: "https://robu.in/product/breadboard-830-points/",
    operatingVoltage: "N/A",
    currentConsumption: "N/A",
    communicationProtocol: "N/A",
    pins: "Tie-point contacts",
    compatibleBoards: ["Universal"],
    applications: ["Prototyping", "Education", "Testing"],
    exampleProjects: [],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-01-12",
  }),
  makeComponent({
    id: "12",
    slug: "oled-display",
    name: "OLED Display 0.96\"",
    category: "displays",
    categoryLabel: "Display",
    shortDescription: "128×64 I2C OLED screen for compact data visualization.",
    description: "SSD1306 monochrome OLED with I2C interface.",
    fullDescription:
      "Small, crisp OLED displays show sensor readings, status messages, and menus on robotics projects. I2C wiring requires only two data pins plus power.",
    specifications: [
      { label: "Resolution", value: "128×64 px" },
      { label: "Interface", value: "I2C" },
      { label: "Driver", value: "SSD1306" },
      { label: "Color", value: "White / Blue" },
    ],
    compatibility: ["Arduino UNO", "ESP32", "Pi"],
    priceRange: "₹150 – ₹280",
    priceValue: 215,
    availability: "in-stock",
    beginnerFriendly: true,
    popular: true,
    rating: 4.6,
    projectCount: 28,
    buyUrl: "https://robu.in/product/0-96-inch-oled-display-i2c/",
    operatingVoltage: "3.3–5V",
    currentConsumption: "20 mA",
    communicationProtocol: "I2C (address 0x3C)",
    pins: "VCC, GND, SDA, SCL",
    compatibleBoards: ["Arduino UNO", "ESP32"],
    applications: ["Status display", "Sensor readout", "Menu UI"],
    exampleProjects: [
      { title: "IoT Weather Station", slug: "iot-weather-station" },
    ],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-03-18",
  }),
  makeComponent({
    id: "13",
    slug: "lcd-16x2",
    name: "LCD 16×2",
    category: "displays",
    categoryLabel: "Display",
    shortDescription: "Classic character LCD with HD44780 controller.",
    description: "16 columns × 2 rows parallel or I2C LCD module.",
    fullDescription:
      "The 16×2 LCD is a staple display in Arduino tutorials. Shows alphanumeric characters for sensor values, menus, and debug output with optional I2C backpack for simplified wiring.",
    specifications: [
      { label: "Size", value: "16×2 characters" },
      { label: "Controller", value: "HD44780" },
      { label: "Backlight", value: "Blue / Green" },
      { label: "Interface", value: "Parallel / I2C" },
    ],
    compatibility: ["Arduino UNO", "ESP32"],
    priceRange: "₹120 – ₹250",
    priceValue: 185,
    availability: "in-stock",
    beginnerFriendly: true,
    popular: false,
    rating: 4.4,
    projectCount: 24,
    buyUrl: "https://robu.in/product/lcd-16x2-i2c/",
    operatingVoltage: "5V",
    currentConsumption: "80 mA with backlight",
    communicationProtocol: "Parallel 4-bit or I2C",
    pins: "VSS, VDD, RS, EN, D4–D7 (or I2C)",
    compatibleBoards: ["Arduino UNO"],
    applications: ["Text display", "Menu systems", "Debug output"],
    exampleProjects: [],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-02-28",
  }),
  makeComponent({
    id: "14",
    slug: "relay-module",
    name: "Relay Module",
    category: "drivers",
    categoryLabel: "Driver",
    shortDescription: "Opto-isolated relay for switching high-voltage loads.",
    description: "Single-channel 10A relay with LED indicator.",
    fullDescription:
      "Relay modules allow microcontrollers to safely switch AC appliances, pumps, and high-current DC loads through an opto-isolated circuit.",
    specifications: [
      { label: "Channels", value: "1 / 2 / 4 / 8" },
      { label: "Load", value: "10A 250V AC" },
      { label: "Trigger", value: "Active LOW" },
      { label: "Isolation", value: "Optocoupler" },
    ],
    compatibility: ["Arduino UNO", "ESP32", "5V logic"],
    priceRange: "₹60 – ₹120",
    priceValue: 90,
    availability: "in-stock",
    beginnerFriendly: true,
    popular: false,
    rating: 4.5,
    projectCount: 19,
    buyUrl: "https://robu.in/product/1-channel-relay-module/",
    operatingVoltage: "5V coil",
    currentConsumption: "70 mA",
    communicationProtocol: "Digital GPIO",
    pins: "VCC, GND, IN, COM, NO, NC",
    compatibleBoards: ["Arduino UNO", "ESP32"],
    applications: ["Home automation", "Pump control", "Light switching"],
    exampleProjects: [
      { title: "Voice Controlled Home", slug: "voice-controlled-home" },
    ],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-05-02",
  }),
  makeComponent({
    id: "15",
    slug: "bluetooth-hc05",
    name: "Bluetooth HC-05",
    category: "communication",
    categoryLabel: "Communication",
    shortDescription: "Classic Bluetooth 2.0 serial module for wireless UART.",
    description: "Master/slave configurable SPP Bluetooth module.",
    fullDescription:
      "The HC-05 enables wireless serial communication between a smartphone and microcontroller. Widely used in Bluetooth-controlled car and remote monitoring projects.",
    specifications: [
      { label: "Protocol", value: "Bluetooth 2.0 SPP" },
      { label: "Range", value: "~10 m" },
      { label: "Baud", value: "9600 default" },
      { label: "Mode", value: "Master / Slave" },
    ],
    compatibility: ["Arduino UNO", "L298N", "Android apps"],
    priceRange: "₹180 – ₹320",
    priceValue: 250,
    availability: "in-stock",
    beginnerFriendly: true,
    popular: true,
    rating: 4.3,
    projectCount: 31,
    buyUrl: "https://robu.in/product/hc-05-bluetooth-module/",
    operatingVoltage: "3.3–5V",
    currentConsumption: "30 mA paired",
    communicationProtocol: "UART serial",
    pins: "VCC, GND, TX, RX, KEY, STATE",
    compatibleBoards: ["Arduino UNO", "ESP32"],
    applications: ["RC cars", "Wireless serial", "Remote control"],
    exampleProjects: [{ title: "Bluetooth Car", slug: "bluetooth-car" }],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-02-15",
  }),
  makeComponent({
    id: "16",
    slug: "wifi-esp8266",
    name: "WiFi ESP8266",
    category: "iot",
    categoryLabel: "IoT",
    shortDescription: "Low-cost Wi-Fi module for IoT and web-connected projects.",
    description: "ESP-01 or NodeMCU form factor with full TCP/IP stack.",
    fullDescription:
      "ESP8266 modules add Wi-Fi connectivity to any project. Can run standalone with MicroPython or act as a Wi-Fi coprocessor for Arduino boards.",
    specifications: [
      { label: "Wi-Fi", value: "802.11 b/g/n" },
      { label: "Flash", value: "1–4 MB" },
      { label: "Clock", value: "80–160 MHz" },
      { label: "Form", value: "ESP-01 / NodeMCU" },
    ],
    compatibility: ["Arduino", "MQTT", "Blynk"],
    priceRange: "₹150 – ₹350",
    priceValue: 250,
    availability: "in-stock",
    beginnerFriendly: true,
    popular: true,
    rating: 4.5,
    projectCount: 27,
    buyUrl: "https://robu.in/product/esp8266-nodemcu/",
    operatingVoltage: "3.3V",
    currentConsumption: "80–170 mA",
    communicationProtocol: "Wi-Fi, UART",
    pins: "GPIO0–GPIO16 (board dependent)",
    compatibleBoards: ["NodeMCU", "Arduino UNO (serial)"],
    applications: ["IoT sensors", "Web servers", "Home automation"],
    exampleProjects: [
      { title: "IoT Weather Station", slug: "iot-weather-station" },
    ],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-03-22",
  }),
  makeComponent({
    id: "17",
    slug: "mpu6050",
    name: "MPU6050",
    category: "sensors",
    categoryLabel: "Sensor",
    shortDescription: "6-axis IMU combining accelerometer and gyroscope.",
    description: "I2C motion tracking module for orientation sensing.",
    fullDescription:
      "The MPU6050 provides 3-axis acceleration and gyroscope data for balance bots, gesture control, and motion tracking applications.",
    specifications: [
      { label: "Axes", value: "3 accel + 3 gyro" },
      { label: "Interface", value: "I2C" },
      { label: "Accel Range", value: "±2g to ±16g" },
      { label: "Gyro Range", value: "±250 to ±2000°/s" },
    ],
    compatibility: ["Arduino UNO", "ESP32", "Pi"],
    priceRange: "₹120 – ₹220",
    priceValue: 170,
    availability: "in-stock",
    beginnerFriendly: false,
    popular: true,
    rating: 4.6,
    projectCount: 21,
    buyUrl: "https://robu.in/product/mpu6050-gyro-sensor/",
    operatingVoltage: "3.3–5V",
    currentConsumption: "3.9 mA",
    communicationProtocol: "I2C (address 0x68)",
    pins: "VCC, GND, SCL, SDA",
    compatibleBoards: ["Arduino UNO", "ESP32"],
    applications: ["Self-balancing", "Gesture control", "Drones"],
    exampleProjects: [
      { title: "Self Balancing Robot", slug: "self-balancing-robot" },
      { title: "Gesture Controlled Robot", slug: "gesture-controlled-robot" },
    ],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-04-08",
  }),
  makeComponent({
    id: "18",
    slug: "flame-sensor",
    name: "Flame Sensor",
    category: "sensors",
    categoryLabel: "Sensor",
    shortDescription: "Detects fire and infrared light sources.",
    description: "IR flame detection module with analog and digital output.",
    fullDescription:
      "Flame sensors detect infrared radiation from fire sources. Used in safety systems, fire-fighting robots, and industrial monitoring prototypes.",
    specifications: [
      { label: "Detection", value: "IR flame" },
      { label: "Range", value: "0–100 cm" },
      { label: "Angle", value: "60°" },
      { label: "Output", value: "Analog + Digital" },
    ],
    compatibility: ["Arduino UNO", "Relay module"],
    priceRange: "₹40 – ₹80",
    priceValue: 60,
    availability: "in-stock",
    beginnerFriendly: true,
    popular: false,
    rating: 4.2,
    projectCount: 8,
    buyUrl: "https://robu.in/product/flame-sensor-module/",
    operatingVoltage: "3.3–5V",
    currentConsumption: "20 mA",
    communicationProtocol: "Analog / Digital GPIO",
    pins: "VCC, GND, AOUT, DOUT",
    compatibleBoards: ["Arduino UNO"],
    applications: ["Fire detection", "Safety systems", "Competition bots"],
    exampleProjects: [],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-05-20",
  }),
  makeComponent({
    id: "19",
    slug: "gas-sensor-mq2",
    name: "Gas Sensor MQ-2",
    category: "sensors",
    categoryLabel: "Sensor",
    shortDescription: "Detects LPG, smoke, alcohol, and combustible gases.",
    description: "Analog gas sensor module with heater element.",
    fullDescription:
      "The MQ-2 sensor detects multiple combustible gases and smoke. Requires warm-up time and calibration for accurate readings in air quality monitoring projects.",
    specifications: [
      { label: "Gases", value: "LPG, smoke, CH4, CO" },
      { label: "Heater", value: "5V required" },
      { label: "Output", value: "Analog" },
      { label: "Warm-up", value: "24–48 hours" },
    ],
    compatibility: ["Arduino UNO", "ESP32", "OLED"],
    priceRange: "₹90 – ₹160",
    priceValue: 125,
    availability: "in-stock",
    beginnerFriendly: false,
    popular: false,
    rating: 4.1,
    projectCount: 11,
    buyUrl: "https://robu.in/product/mq2-gas-sensor-module/",
    operatingVoltage: "5V",
    currentConsumption: "800 mA (heater)",
    communicationProtocol: "Analog ADC",
    pins: "VCC, GND, AOUT, DOUT",
    compatibleBoards: ["Arduino UNO", "ESP32"],
    applications: ["Air quality", "Leak detection", "Safety alarms"],
    exampleProjects: [],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-06-10",
  }),
  makeComponent({
    id: "20",
    slug: "soil-moisture",
    name: "Soil Moisture Sensor",
    category: "sensors",
    categoryLabel: "Sensor",
    shortDescription: "Measures soil water content for agriculture automation.",
    description: "Capacitive or resistive soil moisture probe with analog output.",
    fullDescription:
      "Soil moisture sensors enable automated irrigation systems and smart agriculture projects. Capacitive versions resist corrosion better than resistive probes.",
    specifications: [
      { label: "Type", value: "Capacitive" },
      { label: "Output", value: "Analog 0–3V" },
      { label: "Depth", value: "65 mm probe" },
      { label: "Corrosion", value: "Low (capacitive)" },
    ],
    compatibility: ["Arduino UNO", "ESP32", "Relay"],
    priceRange: "₹50 – ₹120",
    priceValue: 85,
    availability: "in-stock",
    beginnerFriendly: true,
    popular: false,
    rating: 4.3,
    projectCount: 15,
    buyUrl: "https://robu.in/product/capacitive-soil-moisture-sensor/",
    operatingVoltage: "3.3–5V",
    currentConsumption: "5 mA",
    communicationProtocol: "Analog ADC",
    pins: "VCC, GND, AOUT",
    compatibleBoards: ["Arduino UNO", "ESP32"],
    applications: ["Smart irrigation", "Greenhouse", "Plant monitoring"],
    exampleProjects: [
      { title: "Smart Agriculture", slug: "smart-agriculture" },
    ],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-05-15",
  }),
  makeComponent({
    id: "21",
    slug: "pir-motion",
    name: "PIR Motion Sensor",
    category: "sensors",
    categoryLabel: "Sensor",
    shortDescription: "Detects human motion using passive infrared.",
    description: "HC-SR501 adjustable PIR module with 3–7 m range.",
    fullDescription:
      "PIR sensors detect changes in infrared radiation caused by moving objects. Standard in security systems, automatic lighting, and presence-detection robots.",
    specifications: [
      { label: "Range", value: "3–7 m" },
      { label: "Angle", value: "120°" },
      { label: "Delay", value: "Adjustable" },
      { label: "Output", value: "Digital HIGH" },
    ],
    compatibility: ["Arduino UNO", "ESP32", "Relay"],
    priceRange: "₹60 – ₹110",
    priceValue: 85,
    availability: "in-stock",
    beginnerFriendly: true,
    popular: true,
    rating: 4.5,
    projectCount: 18,
    buyUrl: "https://robu.in/product/hc-sr501-pir-sensor/",
    operatingVoltage: "5–20V (5V recommended)",
    currentConsumption: "50 µA idle, 120 µA active",
    communicationProtocol: "Digital GPIO",
    pins: "VCC, OUT, GND",
    compatibleBoards: ["Arduino UNO", "ESP32"],
    applications: ["Security", "Auto lighting", "Presence detection"],
    exampleProjects: [
      { title: "Voice Controlled Home", slug: "voice-controlled-home" },
    ],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-03-30",
  }),
  makeComponent({
    id: "22",
    slug: "dht11",
    name: "DHT11",
    category: "sensors",
    categoryLabel: "Sensor",
    shortDescription: "Basic temperature and humidity sensor.",
    description: "Single-wire digital sensor with ±2°C accuracy.",
    fullDescription:
      "DHT11 provides affordable temperature and humidity readings over a single digital pin. Perfect for weather stations and environmental monitoring beginners.",
    specifications: [
      { label: "Temp Range", value: "0–50°C" },
      { label: "Humidity", value: "20–90% RH" },
      { label: "Accuracy", value: "±2°C, ±5% RH" },
      { label: "Interface", value: "1-wire digital" },
    ],
    compatibility: ["Arduino UNO", "ESP32", "OLED"],
    priceRange: "₹50 – ₹90",
    priceValue: 70,
    availability: "in-stock",
    beginnerFriendly: true,
    popular: true,
    rating: 4.4,
    projectCount: 26,
    buyUrl: "https://robu.in/product/dht11-temperature-humidity-sensor/",
    operatingVoltage: "3.3–5V",
    currentConsumption: "0.3–2.5 mA",
    communicationProtocol: "Custom 1-wire",
    pins: "VCC, DATA, GND",
    compatibleBoards: ["Arduino UNO", "ESP32"],
    applications: ["Weather stations", "Greenhouse", "HVAC monitoring"],
    exampleProjects: [
      { title: "IoT Weather Station", slug: "iot-weather-station" },
    ],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-02-05",
  }),
  makeComponent({
    id: "23",
    slug: "dht22",
    name: "DHT22",
    category: "sensors",
    categoryLabel: "Sensor",
    shortDescription: "High-accuracy temperature and humidity sensor.",
    description: "AM2302 sensor with ±0.5°C temperature accuracy.",
    fullDescription:
      "DHT22 (AM2302) offers improved accuracy over DHT11 with wider measurement ranges. Ideal for projects requiring reliable environmental data logging.",
    specifications: [
      { label: "Temp Range", value: "−40–80°C" },
      { label: "Humidity", value: "0–100% RH" },
      { label: "Accuracy", value: "±0.5°C, ±2% RH" },
      { label: "Interface", value: "1-wire digital" },
    ],
    compatibility: ["Arduino UNO", "ESP32", "OLED"],
    priceRange: "₹180 – ₹280",
    priceValue: 230,
    availability: "in-stock",
    beginnerFriendly: true,
    popular: false,
    rating: 4.6,
    projectCount: 17,
    buyUrl: "https://robu.in/product/dht22-am2302-sensor/",
    operatingVoltage: "3.3–6V",
    currentConsumption: "1–2.5 mA",
    communicationProtocol: "Custom 1-wire",
    pins: "VCC, DATA, GND",
    compatibleBoards: ["Arduino UNO", "ESP32"],
    applications: ["Precision weather", "Data logging", "Climate control"],
    exampleProjects: [
      { title: "Weather Monitoring Station", slug: "weather-monitoring-station" },
    ],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-04-25",
  }),
  makeComponent({
    id: "24",
    slug: "buzzer",
    name: "Buzzer",
    category: "sensors",
    categoryLabel: "Actuator",
    shortDescription: "Active piezo buzzer for alerts and tone generation.",
    description: "5V active buzzer module with built-in oscillator.",
    fullDescription:
      "Active buzzers produce a fixed tone when powered, while passive buzzers can generate varied tones via PWM. Essential for alarms and feedback in robot projects.",
    specifications: [
      { label: "Type", value: "Active / Passive" },
      { label: "Voltage", value: "3.3–5V" },
      { label: "Sound", value: "~2.5 kHz" },
      { label: "Diameter", value: "12 mm" },
    ],
    compatibility: ["Arduino UNO", "ESP32"],
    priceRange: "₹15 – ₹40",
    priceValue: 25,
    availability: "in-stock",
    beginnerFriendly: true,
    popular: false,
    rating: 4.5,
    projectCount: 20,
    buyUrl: "https://robu.in/product/active-buzzer-module/",
    operatingVoltage: "3.3–5V",
    currentConsumption: "30 mA",
    communicationProtocol: "Digital GPIO / PWM",
    pins: "VCC, I/O, GND",
    compatibleBoards: ["Arduino UNO", "ESP32"],
    applications: ["Alarms", "Feedback tones", "Proximity alerts"],
    exampleProjects: [],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-01-28",
  }),
  makeComponent({
    id: "25",
    slug: "led-pack",
    name: "LED Pack",
    category: "development-boards",
    categoryLabel: "Components",
    shortDescription: "Assorted 3mm and 5mm LEDs in multiple colors.",
    description: "100-piece LED kit with resistors for breadboard projects.",
    fullDescription:
      "LED packs include red, green, blue, yellow, and white LEDs for status indicators, learning exercises, and circuit prototyping.",
    specifications: [
      { label: "Sizes", value: "3 mm, 5 mm" },
      { label: "Colors", value: "5 colors" },
      { label: "Quantity", value: "100 pcs" },
      { label: "Forward V", value: "1.8–3.2V" },
    ],
    compatibility: ["Breadboard", "Arduino", "Resistors"],
    priceRange: "₹80 – ₹150",
    priceValue: 115,
    availability: "in-stock",
    beginnerFriendly: true,
    popular: true,
    rating: 4.7,
    projectCount: 45,
    buyUrl: "https://robu.in/product/led-assorted-kit/",
    operatingVoltage: "2–3.3V (with resistor)",
    currentConsumption: "20 mA per LED",
    communicationProtocol: "N/A",
    pins: "Anode (+), Cathode (−)",
    compatibleBoards: ["Universal"],
    applications: ["Indicators", "Learning", "Prototyping"],
    exampleProjects: [],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-01-08",
  }),
  makeComponent({
    id: "26",
    slug: "resistor-kit",
    name: "Resistor Kit",
    category: "development-boards",
    categoryLabel: "Components",
    shortDescription: "600-piece assorted resistor kit with labeled values.",
    description: "1/4W carbon film resistors from 10Ω to 1MΩ.",
    fullDescription:
      "Every electronics lab needs a resistor assortment. This kit covers common values for LED current limiting, voltage dividers, and pull-up/pull-down configurations.",
    specifications: [
      { label: "Quantity", value: "600 pcs" },
      { label: "Power", value: "1/4W" },
      { label: "Range", value: "10Ω – 1MΩ" },
      { label: "Tolerance", value: "±5%" },
    ],
    compatibility: ["Breadboard", "All circuits"],
    priceRange: "₹150 – ₹280",
    priceValue: 215,
    availability: "in-stock",
    beginnerFriendly: true,
    popular: true,
    rating: 4.8,
    projectCount: 50,
    buyUrl: "https://robu.in/product/resistor-kit-600pcs/",
    operatingVoltage: "N/A",
    currentConsumption: "N/A",
    communicationProtocol: "N/A",
    pins: "Through-hole leads",
    compatibleBoards: ["Universal"],
    applications: ["Current limiting", "Voltage dividers", "Pull-ups"],
    exampleProjects: [],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-01-05",
  }),
  makeComponent({
    id: "27",
    slug: "capacitor-kit",
    name: "Capacitor Kit",
    category: "development-boards",
    categoryLabel: "Components",
    shortDescription: "Assorted ceramic and electrolytic capacitors.",
    description: "120-value capacitor kit for filtering and timing circuits.",
    fullDescription:
      "Capacitors are used for power supply filtering, decoupling, and timing circuits. This kit includes common ceramic and electrolytic values for prototyping.",
    specifications: [
      { label: "Quantity", value: "120 pcs" },
      { label: "Types", value: "Ceramic + Electrolytic" },
      { label: "Range", value: "10pF – 1000µF" },
      { label: "Voltage", value: "16V–50V" },
    ],
    compatibility: ["Breadboard", "PCB projects"],
    priceRange: "₹180 – ₹320",
    priceValue: 250,
    availability: "in-stock",
    beginnerFriendly: true,
    popular: false,
    rating: 4.6,
    projectCount: 30,
    buyUrl: "https://robu.in/product/capacitor-assorted-kit/",
    operatingVoltage: "N/A",
    currentConsumption: "N/A",
    communicationProtocol: "N/A",
    pins: "Through-hole / SMD mix",
    compatibleBoards: ["Universal"],
    applications: ["Filtering", "Decoupling", "Timing"],
    exampleProjects: [],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-02-01",
  }),
  makeComponent({
    id: "28",
    slug: "battery-holder",
    name: "Battery Holder",
    category: "power",
    categoryLabel: "Power",
    shortDescription: "2×18650 battery holder with cover and wire leads.",
    description: "Dual 18650 series holder with on/off switch option.",
    fullDescription:
      "Battery holders provide secure mounting and wired connections for rechargeable cells. Essential for portable robot power systems.",
    specifications: [
      { label: "Cells", value: "2× 18650" },
      { label: "Output", value: "7.4V series" },
      { label: "Material", value: "ABS + springs" },
      { label: "Switch", value: "Optional inline" },
    ],
    compatibility: ["18650 cells", "L298N", "Robot chassis"],
    priceRange: "₹60 – ₹120",
    priceValue: 90,
    availability: "in-stock",
    beginnerFriendly: true,
    popular: true,
    rating: 4.4,
    projectCount: 35,
    buyUrl: "https://robu.in/product/2x18650-battery-holder/",
    operatingVoltage: "7.4V (2S)",
    currentConsumption: "N/A",
    communicationProtocol: "N/A",
    pins: "Red (+), Black (−) wires",
    compatibleBoards: ["Mobile robots"],
    applications: ["Portable power", "Robot chassis", "Battery packs"],
    exampleProjects: [
      { title: "Obstacle Avoiding Robot", slug: "obstacle-avoiding-robot" },
    ],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-03-10",
  }),
  makeComponent({
    id: "29",
    slug: "18650-battery",
    name: "18650 Battery",
    category: "power",
    categoryLabel: "Power",
    shortDescription: "Rechargeable lithium-ion 18650 cell, 3.7V.",
    description: "2500–3500 mAh protected 18650 cell for robotics.",
    fullDescription:
      "18650 lithium-ion cells offer high energy density for mobile robots. Always use protected cells and proper charging circuits for safety.",
    specifications: [
      { label: "Voltage", value: "3.7V nominal" },
      { label: "Capacity", value: "2500–3500 mAh" },
      { label: "Chemistry", value: "Li-ion" },
      { label: "Size", value: "18×65 mm" },
    ],
    compatibility: ["Battery holder", "TP4056 charger"],
    priceRange: "₹250 – ₹450",
    priceValue: 350,
    availability: "in-stock",
    beginnerFriendly: false,
    popular: true,
    rating: 4.3,
    projectCount: 32,
    buyUrl: "https://www.amazon.in/s?k=18650+battery+protected",
    operatingVoltage: "3.7V (4.2V max charge)",
    currentConsumption: "Up to 10A discharge",
    communicationProtocol: "N/A",
    pins: "Flat top / button top",
    compatibleBoards: ["Battery holders", "Power modules"],
    applications: ["Robot power", "Portable devices", "Battery packs"],
    exampleProjects: [],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-03-12",
  }),
  makeComponent({
    id: "30",
    slug: "power-module",
    name: "Power Module",
    category: "power",
    categoryLabel: "Power",
    shortDescription: "LM2596 buck converter for adjustable voltage output.",
    description: "Step-down regulator from 4–40V to 1.25–35V.",
    fullDescription:
      "Buck converter modules efficiently step down voltage for powering motors, servos, and logic circuits from a single battery source.",
    specifications: [
      { label: "Input", value: "4–40V DC" },
      { label: "Output", value: "1.25–35V" },
      { label: "Current", value: "3A max" },
      { label: "Efficiency", value: "~92%" },
    ],
    compatibility: ["18650", "12V adapter", "Arduino"],
    priceRange: "₹80 – ₹150",
    priceValue: 115,
    availability: "in-stock",
    beginnerFriendly: true,
    popular: true,
    rating: 4.5,
    projectCount: 29,
    buyUrl: "https://robu.in/product/lm2596-buck-converter/",
    operatingVoltage: "4–40V in, adjustable out",
    currentConsumption: "Up to 3A output",
    communicationProtocol: "N/A",
    pins: "IN+, IN−, OUT+, OUT−",
    compatibleBoards: ["Universal"],
    applications: ["Voltage regulation", "Battery projects", "Motor supply"],
    exampleProjects: [],
    datasheetUrl: "#",
    tutorialUrl: "/chatbot",
    addedAt: "2024-04-02",
  }),
];

export function getFeaturedComponent(): ComponentItem {
  return components.find((c) => c.slug === featuredComponentSlug)!;
}

export function getRecommendedComponents(limit = 6): ComponentItem[] {
  return [...components]
    .filter((c) => c.popular)
    .sort((a, b) => b.rating - a.rating)
    .slice(0, limit);
}

export function filterComponents(
  items: ComponentItem[],
  query: string,
  chip: ComponentFilterChip,
  sort: ComponentSort,
): ComponentItem[] {
  let result = [...items];

  if (chip !== "all") {
    result = result.filter((c) => c.category === chip);
  }

  if (query.trim()) {
    const q = query.toLowerCase();
    result = result.filter(
      (c) =>
        c.name.toLowerCase().includes(q) ||
        c.shortDescription.toLowerCase().includes(q) ||
        c.categoryLabel.toLowerCase().includes(q) ||
        c.compatibility.some((x) => x.toLowerCase().includes(q)),
    );
  }

  switch (sort) {
    case "newest":
      result.sort(
        (a, b) =>
          new Date(b.addedAt).getTime() - new Date(a.addedAt).getTime(),
      );
      break;
    case "popular":
      result.sort((a, b) => b.projectCount - a.projectCount);
      break;
    case "price":
      result.sort((a, b) => a.priceValue - b.priceValue);
      break;
    case "alphabetical":
      result.sort((a, b) => a.name.localeCompare(b.name));
      break;
  }

  return result;
}

export function getComponentBySlug(slug: string): ComponentItem | undefined {
  return components.find((c) => c.slug === slug);
}
